version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    stop_signal: SIGKILL
    restart: always
    volumes:
      - ./var/docker/artifacts:/usr/local/sbin
    ports:
      - "8000:80"
  ui:
    image: library/node:14
    volumes:
      - ./web:/app
    working_dir: /app
    stop_signal: SIGKILL
    restart: always
    command: "npm run dev"

  proxy:
    image: library/nginx:1.19
    volumes:
      - ./docker/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    stop_signal: SIGKILL
    restart: always
    depends_on:
      - ui
      - api

  pg:
    image: postgres:13
    stop_signal: SIGKILL
    volumes:
      - ./docker/dbinit/pg:/docker-entrypoint-initdb.d:ro
      - ./var/db/pg_data:/var/lib/postgresql/data
      - ./var/db/dumps:/dumps
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
