name: Heroku
on:
  release:
    types: [ realeased ]
  workflow_dispatch:

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Heroku Docker Container Deploy
        uses: lucassarcanjo/heroku-deploy@2.1.17
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
